name: flutter_bloc_quotes
description: Flutter BLoC Pattern With Rest API

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  http: ^0.13.4
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:

  uses-material-design: true
